---
- name: Install weechat
  pacman: name=weechat state=present

- name: Jail weechat
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/weechat
        state=link
  tags:
    - firejail

- name: Push weechat firejail profile
  copy: src=firejail/weechat.profile dest=/usr/local/etc/firejail/weechat.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail

- name: Install dunst
  pacman: name=dunst state=present
