---
- name: Install pyenv 
  aur: name=pyenv user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur

- name: Install rbenv 
  aur: name=rbenv user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur

- name: Install rbenv install 
  aur: name=ruby-build user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur

- name: Install docker
  pacman: name=docker state=present

- name: Intsall docker-compose
  pacman: name=docker-compose state=present

- name: Enable docker service in systemd
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Install mysql
  pacman: name=mariadb state=present
