---
- name: Install rofi
  pacman: name=rofi state=present
  tags:
    - rofi

- name: Install rofi-pass
  aur: name=rofi-pass user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur
    - rofi

- name: Install i3-wm for rofi window switching
  pacman: name=i3-wm state=present
  tags:
    - rofi
