---
- name: Install Steam
  pacman: name=steam state=present
# To use the multilib repository, uncomment the [multilib] section in  /etc/pacman.conf

#- name: Install discord 
#  aur: name=discord user={{ user.name }} dir={{ ansible_aur_dir }}
#  tags:
#    - aur
#
