---
- name: Install polybar
  aur: name=polybar user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur

- name: Intsall jsoncpp (dependency of polybar for i3)
  pacman:
    name: jsoncpp
    state: present

- name: Create polybar config dir
  file: 
    path: /home/{{ user.name }}/.config/polybar/
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy over polybar config
  copy: src=config dest=/home/{{ user.name }}/.config/polybar/config
