---
- name: Install i3
  pacman: name=i3 state=present

- name: Install compton
  pacman: name=compton state=present

- name: Install rofi
  pacman: name=rofi state=present
  tags:
    - rofi

- name: Install rofi-pass
  aur: name=rofi-pass user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur
    - rofi

- name: Install i3-wm for rofi window switching
  pacman: name=i3-wm state=present
  tags:
    - rofi

- name: Install screenshot utility
  pacman: name=scrot state=present

- name: Install polybar 
  aur: name=polybar user={{ user.name }} dir={{ ansible_aur_dir }}
  tags:
    - aur

